export const ingestionSources = [
  {
    name: "Red Ayuda Venezuela",
    url: "https://redayudavenezuela.com",
    type: "WEBSITE",
    trustLevel: "medium",
    connector: "html",
    enabled: true,
    priority: ["missing_person", "hospitalized_person", "trapped_person", "safe_person"],
  },
  {
    name: "VzlAyuda",
    url: "https://vzlayuda.com",
    type: "WEBSITE",
    trustLevel: "medium",
    connector: "html",
    enabled: true,
    priority: ["missing_person", "hospitalized_person", "safe_person", "help_center"],
  },
  {
    name: "Red Ayuda Venezuela - Puntos de ayuda",
    url: "https://redayudavenezuela.com/puntos-de-ayuda/",
    type: "WEBSITE",
    trustLevel: "medium",
    connector: "html",
    enabled: true,
    priority: ["collection_center", "help_center", "shelter", "medical_point"],
  },
  {
    name: "VzlAyuda - Centros y ofrecimientos",
    url: "https://vzlayuda.com",
    type: "WEBSITE",
    trustLevel: "medium",
    connector: "html",
    enabled: true,
    priority: ["collection_center", "water_point", "food_point", "medical_point", "volunteer_center"],
  },
  {
    name: "ReliefWeb Venezuela",
    url: "https://reliefweb.int/country/ven",
    type: "WEBSITE",
    trustLevel: "high",
    connector: "reliefweb_api",
    apiUrl: "https://api.reliefweb.int/v1/reports?appname=rescuenet-venezuela&profile=list&preset=latest&limit=50&query[value]=Venezuela",
    enabled: true,
    priority: ["help_center", "donation_need", "medical_point"],
  },
  {
    name: "ReliefWeb Venezuela Disasters",
    url: "https://reliefweb.int/disasters?search=Venezuela",
    type: "API",
    trustLevel: "high",
    connector: "reliefweb_api",
    apiUrl: "https://api.reliefweb.int/v1/disasters?appname=rescuenet-venezuela&profile=list&limit=50&query[value]=Venezuela",
    enabled: true,
    priority: ["damage_report", "donation_need", "help_center"],
  },
  {
    name: "IFRC GO Venezuela",
    url: "https://go.ifrc.org/countries/190",
    type: "WEBSITE",
    trustLevel: "high",
    connector: "html",
    enabled: true,
    priority: ["help_center", "medical_point", "donation_need"],
  },
  {
    name: "Caritas Venezuela",
    url: "https://caritasvenezuela.org",
    type: "WEBSITE",
    trustLevel: "high",
    connector: "html",
    enabled: true,
    priority: ["collection_center", "help_center", "food_point", "medical_point"],
  },
  {
    name: "El Pitazo",
    url: "https://elpitazo.net",
    type: "WEBSITE",
    trustLevel: "recognized_media",
    connector: "html",
    enabled: true,
    priority: ["damage_report", "collection_center", "donation_need"],
  },
  {
    name: "El Diario",
    url: "https://eldiario.com",
    type: "WEBSITE",
    trustLevel: "recognized_media",
    connector: "html",
    enabled: true,
    priority: ["damage_report", "collection_center", "donation_need"],
  },
];

export function enabledSources() {
  return ingestionSources.filter((source) => source.enabled);
}
