export const ingestionSources = [
  {
    name: "Venezuela Te Busca",
    aliases: ["venezuelatebusca", "all-persons"],
    url: "https://venezuelatebusca.com",
    type: "WEBSITE",
    trustLevel: "medium",
    connector: "venezuela_te_busca",
    enabled: true,
    priority: ["missing_person", "safe_person", "hospitalized_person", "rescued_person"],
  },
  {
    name: "Desaparecidos Terremoto Venezuela",
    aliases: ["desaparecidos", "desaparecidosterremotovenezuela", "all-persons"],
    url: "https://desaparecidosterremotovenezuela.com",
    apiBase: "https://desaparecidos-terremoto-api.theempire.tech/api",
    type: "WEBSITE",
    trustLevel: "medium",
    connector: "desaparecidos_terremoto",
    enabled: true,
    priority: ["missing_person", "safe_person", "hospitalized_person"],
  },
  {
    name: "Encuentralos",
    aliases: ["encuentralos", "all-persons"],
    url: "https://encuentralos.tecnosoft.dev",
    type: "WEBSITE",
    trustLevel: "medium",
    connector: "encuentralos",
    enabled: true,
    priority: ["missing_person", "safe_person", "rescued_person", "shelter", "donation_need"],
  },
  {
    name: "TerremotoVenezuela.app",
    aliases: ["terremotovenezuela", "all-persons"],
    url: "https://terremotovenezuela.app",
    type: "WEBSITE",
    trustLevel: "medium",
    connector: "terremoto_venezuela",
    enabled: true,
    priority: ["missing_person", "trapped_person", "safe_person", "rescued_person", "damage_report"],
  },
  {
    name: "Red Ayuda Venezuela",
    aliases: ["redayuda", "all-persons"],
    url: "https://redayudavenezuela.com",
    type: "WEBSITE",
    trustLevel: "medium",
    connector: "html",
    enabled: true,
    priority: ["missing_person", "hospitalized_person", "trapped_person", "safe_person"],
  },
  {
    name: "VzlAyuda",
    aliases: ["vzlayuda", "all-persons"],
    url: "https://vzlayuda.com",
    type: "WEBSITE",
    trustLevel: "medium",
    connector: "html",
    enabled: true,
    priority: ["missing_person", "hospitalized_person", "safe_person", "help_center"],
  },
  {
    name: "Red Ayuda Venezuela - Puntos de ayuda",
    url: "https://redayudavenezuela.com/puntos-de-ayuda/",
    type: "WEBSITE",
    trustLevel: "medium",
    connector: "html",
    enabled: true,
    priority: ["collection_center", "help_center", "shelter", "medical_point"],
  },
  {
    name: "VzlAyuda - Centros y ofrecimientos",
    url: "https://vzlayuda.com",
    type: "WEBSITE",
    trustLevel: "medium",
    connector: "html",
    enabled: true,
    priority: ["collection_center", "water_point", "food_point", "medical_point", "volunteer_center"],
  },
  {
    name: "ReliefWeb Venezuela",
    url: "https://reliefweb.int/country/ven",
    type: "WEBSITE",
    trustLevel: "high",
    connector: "reliefweb_api",
    apiUrl: "https://api.reliefweb.int/v1/reports?appname=rescuenet-venezuela&profile=list&preset=latest&limit=50&query[value]=Venezuela",
    enabled: true,
    priority: ["help_center", "donation_need", "medical_point"],
  },
  {
    name: "ReliefWeb Venezuela Disasters",
    url: "https://reliefweb.int/disasters?search=Venezuela",
    type: "API",
    trustLevel: "high",
    connector: "reliefweb_api",
    apiUrl: "https://api.reliefweb.int/v1/disasters?appname=rescuenet-venezuela&profile=list&limit=50&query[value]=Venezuela",
    enabled: true,
    priority: ["damage_report", "donation_need", "help_center"],
  },
  {
    name: "IFRC GO Venezuela",
    url: "https://go.ifrc.org/countries/190",
    type: "WEBSITE",
    trustLevel: "high",
    connector: "html",
    enabled: true,
    priority: ["help_center", "medical_point", "donation_need"],
  },
  {
    name: "Caritas Venezuela",
    url: "https://caritasvenezuela.org",
    type: "WEBSITE",
    trustLevel: "high",
    connector: "html",
    enabled: true,
    priority: ["collection_center", "help_center", "food_point", "medical_point"],
  },
  {
    name: "El Pitazo",
    url: "https://elpitazo.net",
    type: "WEBSITE",
    trustLevel: "recognized_media",
    connector: "html",
    enabled: true,
    priority: ["damage_report", "collection_center", "donation_need"],
  },
  {
    name: "El Diario",
    url: "https://eldiario.com",
    type: "WEBSITE",
    trustLevel: "recognized_media",
    connector: "html",
    enabled: true,
    priority: ["damage_report", "collection_center", "donation_need"],
  },
];

export function enabledSources() {
  return ingestionSources.filter((source) => source.enabled);
}
