export const publicRoutes = [
  { method: "POST", path: "/api/emergency", purpose: "Public emergency submission" },
  { method: "GET", path: "/api/emergency/public", purpose: "Public sanitized emergency feed" },
  { method: "POST", path: "/api/safe", purpose: "Public safe report" },
  { method: "GET", path: "/api/safe/public", purpose: "Public sanitized safe reports" },
  { method: "POST", path: "/api/missing", purpose: "Public missing person report" },
  { method: "GET", path: "/api/missing/public", purpose: "Public sanitized missing reports" },
  { method: "GET", path: "/api/rescued/public", purpose: "Public sanitized rescued people" },
  { method: "POST", path: "/api/rescued/report", purpose: "Public rescued person report pending review" },
  { method: "GET", path: "/api/hospitals/public", purpose: "Public hospitals" },
  { method: "GET", path: "/api/shelters/public", purpose: "Public shelters" },
  { method: "GET", path: "/api/map/public", purpose: "Public map" },
  { method: "GET", path: "/api/dashboard/public", purpose: "Public dashboard" },
  { method: "GET", path: "/api/organizations/public", purpose: "Public organizations" },
  { method: "GET", path: "/api/donations/public", purpose: "Public donation summary" },
  { method: "GET", path: "/api/help-centers/public", purpose: "Public shelters and hospitals" },
];

export const protectedSensitiveRoutes = [
  "GET /api/emergency",
  "GET /api/emergency/:id/full",
  "PATCH /api/emergency/:id",
  "GET /api/missing/:id/full",
  "GET /api/rescued/:id/full",
  "PATCH /api/rescued/:id",
  "POST /api/hospitals",
  "PATCH /api/hospitals/:id",
  "POST /api/shelters",
  "PATCH /api/shelters/:id",
  "POST /api/organizations",
  "PATCH /api/organizations/:id",
  "POST /api/donations/verified",
  "GET /api/admin/*",
  "GET /api/audit/*",
  "POST /api/import/*",
  "GET /api/import/*",
  "POST /api/uploads/private",
];
