export const PERMISSIONS = {
  EMERGENCY_READ: "emergency:read",
  EMERGENCY_WRITE: "emergency:write",
  MISSING_READ: "missing:read",
  MISSING_WRITE: "missing:write",
  RESCUED_READ: "rescued:read",
  RESCUED_WRITE: "rescued:write",
  HOSPITALS_MANAGE: "hospitals:manage",
  SHELTERS_MANAGE: "shelters:manage",
  ORGANIZATIONS_MANAGE: "organizations:manage",
  DONATIONS_READ: "donations:read",
  DONATIONS_WRITE: "donations:write",
  DASHBOARD_READ: "dashboard:read",
  MAP_READ: "map:read",
  LOGISTICS_READ: "logistics:read",
  LOGISTICS_MANAGE: "logistics:manage",
  AUDIT_READ: "audit:read",
  SYSTEM_ADMIN: "system:admin",
};

export const ROLE_PERMISSIONS = {
  PUBLICO: [PERMISSIONS.EMERGENCY_WRITE, PERMISSIONS.MISSING_WRITE, PERMISSIONS.DONATIONS_READ, PERMISSIONS.DASHBOARD_READ, PERMISSIONS.MAP_READ],
  VICTIMA: [PERMISSIONS.EMERGENCY_WRITE, PERMISSIONS.DASHBOARD_READ, PERMISSIONS.MAP_READ],
  FAMILIAR: [PERMISSIONS.MISSING_WRITE, PERMISSIONS.RESCUED_READ, PERMISSIONS.MISSING_READ],
  RESCATISTA: [PERMISSIONS.EMERGENCY_READ, PERMISSIONS.EMERGENCY_WRITE, PERMISSIONS.RESCUED_READ, PERMISSIONS.RESCUED_WRITE, PERMISSIONS.MAP_READ],
  COORDINADOR: [PERMISSIONS.EMERGENCY_READ, PERMISSIONS.EMERGENCY_WRITE, PERMISSIONS.RESCUED_READ, PERMISSIONS.RESCUED_WRITE, PERMISSIONS.HOSPITALS_MANAGE, PERMISSIONS.SHELTERS_MANAGE, PERMISSIONS.LOGISTICS_READ, PERMISSIONS.LOGISTICS_MANAGE, PERMISSIONS.DASHBOARD_READ, PERMISSIONS.MAP_READ],
  HOSPITAL: [PERMISSIONS.HOSPITALS_MANAGE, PERMISSIONS.RESCUED_READ, PERMISSIONS.RESCUED_WRITE, PERMISSIONS.LOGISTICS_READ],
  REFUGIO: [PERMISSIONS.SHELTERS_MANAGE, PERMISSIONS.RESCUED_READ, PERMISSIONS.RESCUED_WRITE, PERMISSIONS.LOGISTICS_READ],
  ONG: [PERMISSIONS.ORGANIZATIONS_MANAGE, PERMISSIONS.DONATIONS_READ, PERMISSIONS.LOGISTICS_READ, PERMISSIONS.LOGISTICS_MANAGE],
  DONANTE: [PERMISSIONS.DONATIONS_READ, PERMISSIONS.DONATIONS_WRITE],
  GOBIERNO: [PERMISSIONS.DASHBOARD_READ, PERMISSIONS.MAP_READ, PERMISSIONS.EMERGENCY_READ, PERMISSIONS.LOGISTICS_READ, PERMISSIONS.AUDIT_READ],
  ORGANIZACION_INTERNACIONAL: [PERMISSIONS.DASHBOARD_READ, PERMISSIONS.MAP_READ, PERMISSIONS.LOGISTICS_READ, PERMISSIONS.DONATIONS_READ],
  ADMINISTRADOR: Object.values(PERMISSIONS),
};

export function permissionsForRoles(roles = []) {
  return [...new Set(roles.flatMap((role) => ROLE_PERMISSIONS[role] || []))];
}
