-- No-op after migration history repair.
-- The complete operational schema, including humanitarian ingestion models and
-- AffectedZone operational fields, is created in:
-- 20260627000000_init_operational_schema.
--
-- This placeholder keeps the historical migration identifier while allowing
-- clean environments such as Render to use `prisma migrate deploy`.
